### PR TITLE
chore: cleanup and "fix" ws (#10)

### PR DESCRIPTION
**Pull request by truong9c2208**

### CODE REVIEW

**Comment by RFS-ADRENO** [comment]
cai gi day?

**Comment by truong9c2208** [comment]
nhu commit

Vào CN, 22 thg 9, 2024 vào lúc 10:29 RDU ***@***.***> đã
viết:

**Comment by RFS-ADRENO** [comment]
giai thich di

**Comment by truong9c2208** [comment]
xoa package-lock vi cta xai bun.lockb, "fixed" ws, va format lai file test.ts cho dung voi cac api hien tai

**Comment by RFS-ADRENO** [comment]
> xoa package-lock vi cta xai bun.lockb, "fixed" ws, va format lai file test.ts cho dung voi cac api hien tai

fix cai gi cua ws cơ

**Comment by truong9c2208** [comment]
> > xoa package-lock vi cta xai bun.lockb, "fixed" ws, va format lai file test.ts cho dung voi cac api hien tai
> 
> fix cai gi cua ws cơ

that ra la chua fix, chi la xoa nhung cai ma ws tu gui di thoi <(")

**Comment by RFS-ADRENO** [comment]
💩

**Pull request closed without merging**
